### ISSUE TITLE
显示器亮度数据无法同步

### ISSUE THREAD

**Issue by cx1919810** [1812z/PCTools#1]
## 描述

显示器亮度数据无法同步，在 HA 开发者工具中查看 light.pcscreen 实体的属性如下，brightness 不知为何为 null
```yaml
supported_color_modes:
  - brightness
color_mode: brightness
brightness: null
friendly_name: PC 显示器
supported_features: 0
assumed_state: true
```

## 复现步骤

1. 下载最新源码
2. 将 `Update_State_Data.py` 中的 `send_data` 函数中的 `monitor` 参数改为 `monitor=True`
3. 运行 gui.py
4. 在 HA 中添加 light.pcscreen 实体磁贴，发现滑动滑块确实可以调节显示器的亮度，但是如果点进去查看详细信息就会发现亮度没有显示（或者说没有数据），查看实体属性发现 brightness 为 null。如果在 MQTT 中监听 `homeassistant/light/PCscreen/state` 可以看到是正常发送的。

## 预期

实体正常同步当前的显示器亮度

## 环境

Windows 11 24H2 26100.1742
Python 3.12.2
PCTools 源码最新 （并非 releases 中的 v4.3）
Twinkle Tray v1.16.6
HomeAssistant Core 2024.12.5
eclipse-mosquitto 2.0.11
